### PR TITLE
Adding all API's currencies

### PR DESCRIPTION
**Pull request by drowolath**
Adding a method to automatically discover and expose all available currencies on the API

### CODE REVIEW

**Review by ofarukcaki — APPROVED** [review]

**Comment by norech** [comment]
Wow, you did it fast, I planned to make this automatically in a another merge request but not for now x)

I approve your merge request. Haha.

**Comment by drowolath** [comment]
Thanks ^_^

**Comment by omergulen** [comment]
@drowolath and @Norech I thank you both.
Actually, @drowolath  you are better Python programmer than me :)
Thanks for your help :)

**Comment by drowolath** [comment]
Thanks for the dopamine hit @omergulen , glad I could help.

**Pull request merged**
